
;;; $all-vc-particles
'("ab" "ac" "ach" "ad" "adh" "aeb" "aec" "aech" "aed" "aedh" "aef"
  "aeg" "aegh" "aeh" "ael" "aem" "aen" "aeng" "aep" "aer" "aes" "aesh"
  "aet" "aeth" "aev" "aew" "aey" "aez" "aezh" "af" "ag" "agh" "ah"
  "aib" "aic" "aich" "aid" "aidh" "aif" "aig" "aigh" "aih" "ail" "aim"
  "ain" "aing" "aip" "air" "ais" "aish" "ait" "aith" "aiv" "aiw" "aiy"
  "aiz" "aizh" "al" "am" "an" "ang" "aob" "aoc" "aoch" "aod" "aodh"
  "aof" "aog" "aogh" "aoh" "aol" "aom" "aon" "aong" "aop" "aor" "aos"
  "aosh" "aot" "aoth" "aov" "aow" "aoy" "aoz" "aozh" "ap" "ar" "as"
  "ash" "at" "ath" "aub" "auc" "auch" "aud" "audh" "auf" "aug" "augh"
  "auh" "aul" "aum" "aun" "aung" "aup" "aur" "aus" "aush" "aut" "auth"
  "auv" "auw" "auy" "auz" "auzh" "av" "aw" "ay" "az" "azh" "eab" "eac"
  "each" "ead" "eadh" "eaf" "eag" "eagh" "eah" "eal" "eam" "ean"
  "eang" "eap" "ear" "eas" "eash" "eat" "eath" "eav" "eaw" "eay" "eaz"
  "eazh" "eb" "ec" "ech" "ed" "edh" "ef" "eg" "egh" "eh" "eib" "eic"
  "eich" "eid" "eidh" "eif" "eig" "eigh" "eih" "eil" "eim" "ein"
  "eing" "eip" "eir" "eis" "eish" "eit" "eith" "eiv" "eiw" "eiy" "eiz"
  "eizh" "el" "em" "en" "eng" "eob" "eoc" "eoch" "eod" "eodh" "eof"
  "eog" "eogh" "eoh" "eol" "eom" "eon" "eong" "eop" "eor" "eos" "eosh"
  "eot" "eoth" "eov" "eow" "eoy" "eoz" "eozh" "ep" "er" "es" "esh"
  "et" "eth" "eub" "euc" "euch" "eud" "eudh" "euf" "eug" "eugh" "euh"
  "eul" "eum" "eun" "eung" "eup" "eur" "eus" "eush" "eut" "euth" "euv"
  "euw" "euy" "euz" "euzh" "ev" "ew" "ey" "ez" "ezh" "iab" "iac"
  "iach" "iad" "iadh" "iaf" "iag" "iagh" "iah" "ial" "iam" "ian"
  "iang" "iap" "iar" "ias" "iash" "iat" "iath" "iav" "iaw" "iay" "iaz"
  "iazh" "ib" "ic" "ich" "id" "idh" "ieb" "iec" "iech" "ied" "iedh"
  "ief" "ieg" "iegh" "ieh" "iel" "iem" "ien" "ieng" "iep" "ier" "ies"
  "iesh" "iet" "ieth" "iev" "iew" "iey" "iez" "iezh" "if" "ig" "igh"
  "ih" "il" "im" "in" "ing" "iob" "ioc" "ioch" "iod" "iodh" "iof"
  "iog" "iogh" "ioh" "iol" "iom" "ion" "iong" "iop" "ior" "ios" "iosh"
  "iot" "ioth" "iov" "iow" "ioy" "ioz" "iozh" "ip" "ir" "is" "ish"
  "it" "ith" "iub" "iuc" "iuch" "iud" "iudh" "iuf" "iug" "iugh" "iuh"
  "iul" "ium" "iun" "iung" "iup" "iur" "ius" "iush" "iut" "iuth" "iuv"
  "iuw" "iuy" "iuz" "iuzh" "iv" "iw" "iy" "iz" "izh" "oab" "oac"
  "oach" "oad" "oadh" "oaf" "oag" "oagh" "oah" "oal" "oam" "oan"
  "oang" "oap" "oar" "oas" "oash" "oat" "oath" "oav" "oaw" "oay" "oaz"
  "oazh" "ob" "oc" "och" "od" "odh" "oeb" "oec" "oech" "oed" "oedh"
  "oef" "oeg" "oegh" "oeh" "oel" "oem" "oen" "oeng" "oep" "oer" "oes"
  "oesh" "oet" "oeth" "oev" "oew" "oey" "oez" "oezh" "of" "og" "ogh"
  "oh" "oib" "oic" "oich" "oid" "oidh" "oif" "oig" "oigh" "oih" "oil"
  "oim" "oin" "oing" "oip" "oir" "ois" "oish" "oit" "oith" "oiv" "oiw"
  "oiy" "oiz" "oizh" "ol" "om" "on" "ong" "op" "or" "os" "osh" "ot"
  "oth" "oub" "ouc" "ouch" "oud" "oudh" "ouf" "oug" "ough" "ouh" "oul"
  "oum" "oun" "oung" "oup" "our" "ous" "oush" "out" "outh" "ouv" "ouw"
  "ouy" "ouz" "ouzh" "ov" "ow" "oy" "oz" "ozh" "uab" "uac" "uach"
  "uad" "uadh" "uaf" "uag" "uagh" "uah" "ual" "uam" "uan" "uang" "uap"
  "uar" "uas" "uash" "uat" "uath" "uav" "uaw" "uay" "uaz" "uazh" "ub"
  "uc" "uch" "ud" "udh" "ueb" "uec" "uech" "ued" "uedh" "uef" "ueg"
  "uegh" "ueh" "uel" "uem" "uen" "ueng" "uep" "uer" "ues" "uesh" "uet"
  "ueth" "uev" "uew" "uey" "uez" "uezh" "uf" "ug" "ugh" "uh" "uib"
  "uic" "uich" "uid" "uidh" "uif" "uig" "uigh" "uih" "uil" "uim" "uin"
  "uing" "uip" "uir" "uis" "uish" "uit" "uith" "uiv" "uiw" "uiy" "uiz"
  "uizh" "ul" "um" "un" "ung" "uob" "uoc" "uoch" "uod" "uodh" "uof"
  "uog" "uogh" "uoh" "uol" "uom" "uon" "uong" "uop" "uor" "uos" "uosh"
  "uot" "uoth" "uov" "uow" "uoy" "uoz" "uozh" "up" "ur" "us" "ush"
  "ut" "uth" "uv" "uw" "uy" "uz" "uzh" "áb" "ác" "ách" "ád" "ádh" "áf"
  "ág" "ágh" "áh" "ál" "ám" "án" "áng" "áp" "ár" "ás" "ásh" "át" "áth"
  "áv" "áw" "áy" "áz" "ázh" "éb" "éc" "éch" "éd" "édh" "éf" "ég" "égh"
  "éh" "él" "ém" "én" "éng" "ép" "ér" "és" "ésh" "ét" "éth" "év" "éw"
  "éy" "éz" "ézh" "íb" "íc" "ích" "íd" "ídh" "íf" "íg" "ígh" "íh" "íl"
  "ím" "ín" "íng" "íp" "ír" "ís" "ísh" "ít" "íth" "ív" "íw" "íy" "íz"
  "ízh" "ób" "óc" "óch" "ód" "ódh" "óf" "óg" "ógh" "óh" "ól" "óm" "ón"
  "óng" "óp" "ór" "ós" "ósh" "ót" "óth" "óv" "ów" "óy" "óz" "ózh" "úb"
  "úc" "úch" "úd" "údh" "úf" "úg" "úgh" "úh" "úl" "úm" "ún" "úng" "úp"
  "úr" "ús" "úsh" "út" "úth" "úv" "úw" "úy" "úz" "úzh")
