(in-package :fi)


(defun all-vc-particles ()
  (reduce #'append
          (loop for v in $vowels
             collect (loop for c in $cv-particle-finals
                          collect (concatenate 'string v c)))))

(defparameter $all-vc-particles
  '("am" "av" "ath" "adh" "at" "ad" "an" "ar" "al" "as" "az" "ash" "azh"
    "ac" "ag" "aw" "arm" "alm" "arv" "alv" "anth" "arth" "alth" "andh"
    "ardh" "aldh" "ant" "art" "ast" "alt" "and" "ard" "ald" "arn" "ars"
    "ats" "acs" "arz" "adz" "agz" "arsh" "atsh" "acsh" "arsh" "adzh"
    "agzh" "anc" "arc" "asc" "ang" "arg" "azg"

    "em" "ev" "eth" "edh"
    "et" "ed" "en" "er" "el" "es" "ez" "esh" "ezh" "ec" "eg" "ew" "erm"
    "elm" "erv" "elv" "enth" "erth" "elth" "endh" "erdh" "eldh" "ent"
    "ert" "est" "elt" "end" "erd" "eld" "ern" "ers" "ets" "ecs" "erz"
    "edz" "egz" "ersh" "etsh" "ecsh" "ersh" "edzh" "egzh" "enc" "erc"
    "esc" "eng" "erg" "ezg"

    "im" "iv" "ith" "idh" "it" "id" "in" "ir"
    "il" "is" "iz" "ish" "izh" "ic" "ig" "iw" "irm" "ilm" "irv" "ilv"
    "inth" "irth" "ilth" "indh" "irdh" "ildh" "int" "irt" "ist" "ilt"
    "ind" "ird" "ild" "irn" "irs" "its" "ics" "irz" "idz" "igz" "irsh"
    "itsh" "icsh" "irsh" "idzh" "igzh" "inc" "irc" "isc" "ing" "irg"
    "izg" "im" "iv" "ith" "idh" "it" "id" "in" "ir" "il" "is" "iz" "ish"
    "izh" "ic" "ig" "iw" "irm" "ilm" "irv" "ilv" "inth" "irth" "ilth"
    "indh" "irdh" "ildh" "int" "irt" "ist" "ilt" "ind" "ird" "ild" "irn"
    "irs" "its" "ics" "irz" "idz" "igz" "irsh" "itsh" "icsh" "irsh"
    "idzh" "igzh" "inc" "irc" "isc" "ing" "irg" "izg" "im" "iv" "ith"
    "idh" "it" "id" "in" "ir" "il" "is" "iz" "ish" "izh" "ic" "ig" "iw"
    "irm" "ilm" "irv" "ilv" "inth" "irth" "ilth" "indh" "irdh" "ildh"
    "int" "irt" "ist" "ilt" "ind" "ird" "ild" "irn" "irs" "its" "ics"
    "irz" "idz" "igz" "irsh" "itsh" "icsh" "irsh" "idzh" "igzh" "inc"
    "irc" "isc" "ing" "irg" "izg"

    "ám" "áv" "áth" "ádh" "át" "ád" "án"
    "ár" "ál" "ás" "áz" "ásh" "ázh" "ác" "ág" "áw" "árm" "álm" "árv"
    "álv" "ánth" "árth" "álth" "ándh" "árdh" "áldh" "ánt" "árt" "ást"
    "ált" "ánd" "árd" "áld" "árn" "árs" "áts" "ács" "árz" "ádz" "ágz"
    "ársh" "átsh" "ácsh" "ársh" "ádzh" "ágzh" "ánc" "árc" "ásc" "áng"
    "árg" "ázg"

    "ém" "év" "éth" "édh" "ét" "éd" "én" "ér" "él" "és" "éz"
    "ésh" "ézh" "éc" "ég" "éw" "érm" "élm" "érv" "élv" "énth" "érth"
    "élth" "éndh" "érdh" "éldh" "ént" "ért" "ést" "élt" "énd" "érd"
    "éld" "érn" "érs" "éts" "écs" "érz" "édz" "égz" "érsh" "étsh" "écsh"
    "érsh" "édzh" "égzh" "énc" "érc" "ésc" "éng" "érg" "ézg"

    "ím" "ív"
    "íth" "ídh" "ít" "íd" "ín" "ír" "íl" "ís" "íz" "ísh" "ízh" "íc" "íg"
    "íw" "írm" "ílm" "írv" "ílv" "ínth" "írth" "ílth" "índh" "írdh"
    "íldh" "ínt" "írt" "íst" "ílt" "índ" "írd" "íld" "írn" "írs" "íts"
    "ícs" "írz" "ídz" "ígz" "írsh" "ítsh" "ícsh" "írsh" "ídzh" "ígzh"
    "ínc" "írc" "ísc" "íng" "írg" "ízg"

    "óm" "óv" "óth" "ódh" "ót" "ód"
    "ón" "ór" "ól" "ós" "óz" "ósh" "ózh" "óc" "óg" "ów" "órm" "ólm"
    "órv" "ólv" "ónth" "órth" "ólth" "óndh" "órdh" "óldh" "ónt" "órt"
    "óst" "ólt" "ónd" "órd" "óld" "órn" "órs" "óts" "ócs" "órz" "ódz"
    "ógz" "órsh" "ótsh" "ócsh" "órsh" "ódzh" "ógzh" "ónc" "órc" "ósc"
    "óng" "órg" "ózg"

    "úm" "úv" "úth" "údh" "út" "úd" "ún" "úr" "úl"
    "ús" "úz" "úsh" "úzh" "úc" "úg" "úw" "úrm" "úlm" "úrv" "úlv" "únth"
    "úrth" "últh" "úndh" "úrdh" "úldh" "únt" "úrt" "úst" "últ" "únd"
    "úrd" "úld" "úrn" "úrs" "úts" "úcs" "úrz" "údz" "úgz" "úrsh" "útsh"
    "úcsh" "úrsh" "údzh" "úgzh" "únc" "úrc" "úsc" "úng" "úrg" "úzg"

    "am"
    "av" "ath" "adh" "at" "ad" "an" "ar" "al" "as" "az" "ash" "azh" "ac"
    "ag" "aw" "arm" "alm" "arv" "alv" "anth" "arth" "alth" "andh" "ardh"
    "aldh" "ant" "art" "ast" "alt" "and" "ard" "ald" "arn" "ars" "ats"
    "acs" "arz" "adz" "agz" "arsh" "atsh" "acsh" "arsh" "adzh" "agzh"
    "anc" "arc" "asc" "ang" "arg" "azg"

    "em" "ev" "eth" "edh" "et" "ed"
    "en" "er" "el" "es" "ez" "esh" "ezh" "ec" "eg" "ew" "erm" "elm"
    "erv" "elv" "enth" "erth" "elth" "endh" "erdh" "eldh" "ent" "ert"
    "est" "elt" "end" "erd" "eld" "ern" "ers" "ets" "ecs" "erz" "edz"
    "egz" "ersh" "etsh" "ecsh" "ersh" "edzh" "egzh" "enc" "erc" "esc"
    "eng" "erg" "ezg"

    "im" "iv" "ith" "idh" "it" "id" "in" "ir" "il"
    "is" "iz" "ish" "izh" "ic" "ig" "iw" "irm" "ilm" "irv" "ilv" "inth"
    "irth" "ilth" "indh" "irdh" "ildh" "int" "irt" "ist" "ilt" "ind"
    "ird" "ild" "irn" "irs" "its" "ics" "irz" "idz" "igz" "irsh" "itsh"
    "icsh" "irsh" "idzh" "igzh" "inc" "irc" "isc" "ing" "irg" "izg"

    "om"
    "ov" "oth" "odh" "ot" "od" "on" "or" "ol" "os" "oz" "osh" "ozh" "oc"
    "og" "ow" "orm" "olm" "orv" "olv" "onth" "orth" "olth" "ondh" "ordh"
    "oldh" "ont" "ort" "ost" "olt" "ond" "ord" "old" "orn" "ors" "ots"
    "ocs" "orz" "odz" "ogz" "orsh" "otsh" "ocsh" "orsh" "odzh" "ogzh"
    "onc" "orc" "osc" "ong" "org" "ozg"

    "um" "uv" "uth" "udh" "ut" "ud"
    "un" "ur" "ul" "us" "uz" "ush" "uzh" "uc" "ug" "uw" "urm" "ulm"
    "urv" "ulv" "unth" "urth" "ulth" "undh" "urdh" "uldh" "unt" "urt"
    "ust" "ult" "und" "urd" "uld" "urn" "urs" "uts" "ucs" "urz" "udz"
    "ugz" "ursh" "utsh" "ucsh" "ursh" "udzh" "ugzh" "unc" "urc" "usc"
    "ung" "urg" "uzg"

    "aem" "aev" "aeth" "aedh" "aet" "aed" "aen" "aer"
    "ael" "aes" "aez" "aesh" "aezh" "aec" "aeg" "aew" "aerm" "aelm"
    "aerv" "aelv" "aenth" "aerth" "aelth" "aendh" "aerdh" "aeldh" "aent"
    "aert" "aest" "aelt" "aend" "aerd" "aeld" "aern" "aers" "aets"
    "aecs" "aerz" "aedz" "aegz" "aersh" "aetsh" "aecsh" "aersh" "aedzh"
    "aegzh" "aenc" "aerc" "aesc" "aeng" "aerg" "aezg"

    "aim" "aiv" "aith"
    "aidh" "ait" "aid" "ain" "air" "ail" "ais" "aiz" "aish" "aizh" "aic"
    "aig" "aiw" "airm" "ailm" "airv" "ailv" "ainth" "airth" "ailth"
    "aindh" "airdh" "aildh" "aint" "airt" "aist" "ailt" "aind" "aird"
    "aild" "airn" "airs" "aits" "aics" "airz" "aidz" "aigz" "airsh"
    "aitsh" "aicsh" "airsh" "aidzh" "aigzh" "ainc" "airc" "aisc" "aing"
    "airg" "aizg"

    "aom" "aov" "aoth" "aodh" "aot" "aod" "aon" "aor"
    "aol" "aos" "aoz" "aosh" "aozh" "aoc" "aog" "aow" "aorm" "aolm"
    "aorv" "aolv" "aonth" "aorth" "aolth" "aondh" "aordh" "aoldh" "aont"
    "aort" "aost" "aolt" "aond" "aord" "aold" "aorn" "aors" "aots"
    "aocs" "aorz" "aodz" "aogz" "aorsh" "aotsh" "aocsh" "aorsh" "aodzh"
    "aogzh" "aonc" "aorc" "aosc" "aong" "aorg" "aozg"

    "aum" "auv" "auth"
    "audh" "aut" "aud" "aun" "aur" "aul" "aus" "auz" "aush" "auzh" "auc"
    "aug" "auw" "aurm" "aulm" "aurv" "aulv" "aunth" "aurth" "aulth"
    "aundh" "aurdh" "auldh" "aunt" "aurt" "aust" "ault" "aund" "aurd"
    "auld" "aurn" "aurs" "auts" "aucs" "aurz" "audz" "augz" "aursh"
    "autsh" "aucsh" "aursh" "audzh" "augzh" "aunc" "aurc" "ausc" "aung"
    "aurg" "auzg"

    "eam" "eav" "eath" "eadh" "eat" "ead" "ean" "ear"
    "eal" "eas" "eaz" "eash" "eazh" "eac" "eag" "eaw" "earm" "ealm"
    "earv" "ealv" "eanth" "earth" "ealth" "eandh" "eardh" "ealdh" "eant"
    "eart" "east" "ealt" "eand" "eard" "eald" "earn" "ears" "eats"
    "eacs" "earz" "eadz" "eagz" "earsh" "eatsh" "eacsh" "earsh" "eadzh"
    "eagzh" "eanc" "earc" "easc" "eang" "earg" "eazg"

    "eim" "eiv" "eith"
    "eidh" "eit" "eid" "ein" "eir" "eil" "eis" "eiz" "eish" "eizh" "eic"
    "eig" "eiw" "eirm" "eilm" "eirv" "eilv" "einth" "eirth" "eilth"
    "eindh" "eirdh" "eildh" "eint" "eirt" "eist" "eilt" "eind" "eird"
    "eild" "eirn" "eirs" "eits" "eics" "eirz" "eidz" "eigz" "eirsh"
    "eitsh" "eicsh" "eirsh" "eidzh" "eigzh" "einc" "eirc" "eisc" "eing"
    "eirg" "eizg"

    "eom" "eov" "eoth" "eodh" "eot" "eod" "eon" "eor"
    "eol" "eos" "eoz" "eosh" "eozh" "eoc" "eog" "eow" "eorm" "eolm"
    "eorv" "eolv" "eonth" "eorth" "eolth" "eondh" "eordh" "eoldh" "eont"
    "eort" "eost" "eolt" "eond" "eord" "eold" "eorn" "eors" "eots"
    "eocs" "eorz" "eodz" "eogz" "eorsh" "eotsh" "eocsh" "eorsh" "eodzh"
    "eogzh" "eonc" "eorc" "eosc" "eong" "eorg" "eozg"

    "eum" "euv" "euth"
    "eudh" "eut" "eud" "eun" "eur" "eul" "eus" "euz" "eush" "euzh" "euc"
    "eug" "euw" "eurm" "eulm" "eurv" "eulv" "eunth" "eurth" "eulth"
    "eundh" "eurdh" "euldh" "eunt" "eurt" "eust" "eult" "eund" "eurd"
    "euld" "eurn" "eurs" "euts" "eucs" "eurz" "eudz" "eugz" "eursh"
    "eutsh" "eucsh" "eursh" "eudzh" "eugzh" "eunc" "eurc" "eusc" "eung"
    "eurg" "euzg"

    "iam" "iav" "iath" "iadh" "iat" "iad" "ian" "iar"
    "ial" "ias" "iaz" "iash" "iazh" "iac" "iag" "iaw" "iarm" "ialm"
    "iarv" "ialv" "ianth" "iarth" "ialth" "iandh" "iardh" "ialdh" "iant"
    "iart" "iast" "ialt" "iand" "iard" "iald" "iarn" "iars" "iats"
    "iacs" "iarz" "iadz" "iagz" "iarsh" "iatsh" "iacsh" "iarsh" "iadzh"
    "iagzh" "ianc" "iarc" "iasc" "iang" "iarg" "iazg"

    "iem" "iev" "ieth"
    "iedh" "iet" "ied" "ien" "ier" "iel" "ies" "iez" "iesh" "iezh" "iec"
    "ieg" "iew" "ierm" "ielm" "ierv" "ielv" "ienth" "ierth" "ielth"
    "iendh" "ierdh" "ieldh" "ient" "iert" "iest" "ielt" "iend" "ierd"
    "ield" "iern" "iers" "iets" "iecs" "ierz" "iedz" "iegz" "iersh"
    "ietsh" "iecsh" "iersh" "iedzh" "iegzh" "ienc" "ierc" "iesc" "ieng"
    "ierg" "iezg"

    "iom" "iov" "ioth" "iodh" "iot" "iod" "ion" "ior"
    "iol" "ios" "ioz" "iosh" "iozh" "ioc" "iog" "iow" "iorm" "iolm"
    "iorv" "iolv" "ionth" "iorth" "iolth" "iondh" "iordh" "ioldh" "iont"
    "iort" "iost" "iolt" "iond" "iord" "iold" "iorn" "iors" "iots"
    "iocs" "iorz" "iodz" "iogz" "iorsh" "iotsh" "iocsh" "iorsh" "iodzh"
    "iogzh" "ionc" "iorc" "iosc" "iong" "iorg" "iozg"

    "ium" "iuv" "iuth"
    "iudh" "iut" "iud" "iun" "iur" "iul" "ius" "iuz" "iush" "iuzh" "iuc"
    "iug" "iuw" "iurm" "iulm" "iurv" "iulv" "iunth" "iurth" "iulth"
    "iundh" "iurdh" "iuldh" "iunt" "iurt" "iust" "iult" "iund" "iurd"
    "iuld" "iurn" "iurs" "iuts" "iucs" "iurz" "iudz" "iugz" "iursh"
    "iutsh" "iucsh" "iursh" "iudzh" "iugzh" "iunc" "iurc" "iusc" "iung"
    "iurg" "iuzg"

    "oam" "oav" "oath" "oadh" "oat" "oad" "oan" "oar"
    "oal" "oas" "oaz" "oash" "oazh" "oac" "oag" "oaw" "oarm" "oalm"
    "oarv" "oalv" "oanth" "oarth" "oalth" "oandh" "oardh" "oaldh" "oant"
    "oart" "oast" "oalt" "oand" "oard" "oald" "oarn" "oars" "oats"
    "oacs" "oarz" "oadz" "oagz" "oarsh" "oatsh" "oacsh" "oarsh" "oadzh"
    "oagzh" "oanc" "oarc" "oasc" "oang" "oarg" "oazg"

    "oem" "oev" "oeth"
    "oedh" "oet" "oed" "oen" "oer" "oel" "oes" "oez" "oesh" "oezh" "oec"
    "oeg" "oew" "oerm" "oelm" "oerv" "oelv" "oenth" "oerth" "oelth"
    "oendh" "oerdh" "oeldh" "oent" "oert" "oest" "oelt" "oend" "oerd"
    "oeld" "oern" "oers" "oets" "oecs" "oerz" "oedz" "oegz" "oersh"
    "oetsh" "oecsh" "oersh" "oedzh" "oegzh" "oenc" "oerc" "oesc" "oeng"
    "oerg" "oezg"

    "oim" "oiv" "oith" "oidh" "oit" "oid" "oin" "oir"
    "oil" "ois" "oiz" "oish" "oizh" "oic" "oig" "oiw" "oirm" "oilm"
    "oirv" "oilv" "ointh" "oirth" "oilth" "oindh" "oirdh" "oildh" "oint"
    "oirt" "oist" "oilt" "oind" "oird" "oild" "oirn" "oirs" "oits"
    "oics" "oirz" "oidz" "oigz" "oirsh" "oitsh" "oicsh" "oirsh" "oidzh"
    "oigzh" "oinc" "oirc" "oisc" "oing" "oirg" "oizg"

    "oum" "ouv" "outh"
    "oudh" "out" "oud" "oun" "our" "oul" "ous" "ouz" "oush" "ouzh" "ouc"
    "oug" "ouw" "ourm" "oulm" "ourv" "oulv" "ounth" "ourth" "oulth"
    "oundh" "ourdh" "ouldh" "ount" "ourt" "oust" "oult" "ound" "ourd"
    "ould" "ourn" "ours" "outs" "oucs" "ourz" "oudz" "ougz" "oursh"
    "outsh" "oucsh" "oursh" "oudzh" "ougzh" "ounc" "ourc" "ousc" "oung"
    "ourg" "ouzg"

    "uam" "uav" "uath" "uadh" "uat" "uad" "uan" "uar"
    "ual" "uas" "uaz" "uash" "uazh" "uac" "uag" "uaw" "uarm" "ualm"
    "uarv" "ualv" "uanth" "uarth" "ualth" "uandh" "uardh" "ualdh" "uant"
    "uart" "uast" "ualt" "uand" "uard" "uald" "uarn" "uars" "uats"
    "uacs" "uarz" "uadz" "uagz" "uarsh" "uatsh" "uacsh" "uarsh" "uadzh"
    "uagzh" "uanc" "uarc" "uasc" "uang" "uarg" "uazg"

    "uem" "uev" "ueth"
    "uedh" "uet" "ued" "uen" "uer" "uel" "ues" "uez" "uesh" "uezh" "uec"
    "ueg" "uew" "uerm" "uelm" "uerv" "uelv" "uenth" "uerth" "uelth"
    "uendh" "uerdh" "ueldh" "uent" "uert" "uest" "uelt" "uend" "uerd"
    "ueld" "uern" "uers" "uets" "uecs" "uerz" "uedz" "uegz" "uersh"
    "uetsh" "uecsh" "uersh" "uedzh" "uegzh" "uenc" "uerc" "uesc" "ueng"
    "uerg" "uezg"

    "uim" "uiv" "uith" "uidh" "uit" "uid" "uin" "uir"
    "uil" "uis" "uiz" "uish" "uizh" "uic" "uig" "uiw" "uirm" "uilm"
    "uirv" "uilv" "uinth" "uirth" "uilth" "uindh" "uirdh" "uildh" "uint"
    "uirt" "uist" "uilt" "uind" "uird" "uild" "uirn" "uirs" "uits"
    "uics" "uirz" "uidz" "uigz" "uirsh" "uitsh" "uicsh" "uirsh" "uidzh"
    "uigzh" "uinc" "uirc" "uisc" "uing" "uirg" "uizg"

    "uom" "uov" "uoth"
    "uodh" "uot" "uod" "uon" "uor" "uol" "uos" "uoz" "uosh" "uozh" "uoc"
    "uog" "uow" "uorm" "uolm" "uorv" "uolv" "uonth" "uorth" "uolth"
    "uondh" "uordh" "uoldh" "uont" "uort" "uost" "uolt" "uond" "uord"
    "uold" "uorn" "uors" "uots" "uocs" "uorz" "uodz" "uogz" "uorsh"
    "uotsh" "uocsh" "uorsh" "uodzh" "uogzh" "uonc" "uorc" "uosc" "uong"
    "uorg" "uozg"))
